_target_: src.models.vio_module.VIOLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  _partial_: true
  T_0: 25
  T_mult: 1


criterion:
  _target_: src.metrics.weighted_loss.WeightedMSEPoseLoss

net:
  _target_: src.models.components.vio_simple_dense_net.VIOSimpleDenseNet
  seq_len: 11
  channels: 3
  width: 512
  height: 256
  imu_freq: 10
  lin1_size: 32
  lin2_size: 32
  lin3_size: 32
  output_size: 30

metrics_calculator:
  _target_: src.metrics.kitti_metrics_calculator.KITTIMetricsCalculator

tester:
  _target_: src.testers.kitti_tester.KITTITester
  val_seqs: ['05','07', '10']
  data_dir: ${paths.data_dir}/kitti_data
  seq_len: 11
  folder: sequences
  img_w: 512
  img_h: 256

# compile model for faster training with pytorch 2.0
compile: false
